### ISSUE TITLE
Zotonic 1.0 Hackday

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1319]
We’ve planned a Zotonic 1.0 Hackday for September the 23rd! 🌟 🎆 🎈 

Everyone is invited to together hack on Zotonic, share ideas, have a beer, etc. 💡🍻   There will be issues for both experts and beginners to work on. The core Zotonic dev team will be present to help out. Location will be in the centre of Amsterdam (either at Driebit or Hackers & Founders). The goal is to take a significant step towards a stable release by solving as many issues as we can.

Let’s make 2016 the year of Zotonic 1.0! 😄 

/cc @mworrell @arjan @mmzeeman @ArthurClemens @michielklonhammer @driebit/core and more!

Ideas:
### For Erlangers
- [ ] dialyzer (#1322)
- [ ] error & access logs (#1406)
- [x] Binaryfication / cowboy
- [x] Remove acl_rsc_update_check (#1381)
- [ ] Add tests for template filters (#1303)
### For language experts
- [x] Add support for language variations like zh-hk (#499)
- [x] move translations to single file #858
- [ ] Add parameters to translation strings (#608)
### For JavaScript experts
- [ ] Replace JQuery with plain JS (#908)
- [ ] Figure out and document supported browsers (#1100)
### For writers
- [ ] improve missing and faulty translations (https://github.com/driebit/ginger/issues/7)
- [ ] Improve documentation (#1123) 
- [ ] Update docs for 1.0 (#1399)
- [ ] improve coding standards (#1275)
- [x] Document custom filters (#966), external services (#910), `m.config` (#709)
- [ ] document MQTT topics (#1341)
### For search experts
- [ ] Unified search (#1168)
- [ ] Improve search results relevance and ranking
### For Ops experts
- [ ] Letsencrypt - all Zotonic installs default on SSL
- [ ] HSTS headers (#1329)
- [ ] Remove Bash dep (#1365)

**Comment by ddeboer** [comment]
@mworrell Good one, let’s add some ideas here!

**Comment by ArthurClemens** [comment]
I won't be able to join because of holiday.

**Comment by ddeboer** [comment]
We decided to reschedule because of the holidays. So perhaps @ArthurClemens and others can make it on September 23rd?

**Comment by ArthurClemens** [comment]
Perfect.

**Comment by ddeboer** [comment]
Closing, as we had a fun and successful hackday. :wink:
