### ISSUE TITLE
mod_mailinglist: Add optional tracking image for statistics

### ISSUE THREAD

**Issue by arjan** [zotonic/zotonic#487]
Plus rewrite the links in the e-mail so they can be measured individually as well.

This has come from a client request.

 - [ ] Integrate `mod_mailinglist` with `mod_email_status`, remove bounce management of mod_mailinglist
 - [ ] add check in emailer to not send mail for failing addresses (unless special flag set, think of password reset mails or email validation probes)
 - [ ] add template with 1-pixel image for 'read' status of emails
 - [ ] method for urls in emails to register that a link in the email has been followed

cc @mworrell

**Comment by mworrell** [comment]
This can hook into the  `mod_email_status`

**Comment by mworrell** [comment]
Added checkboxes from a previous work-in-progress
